[integator]
test = 2
source_dir = "/Users/mabe/Desktop/Git/Integator"

[[integator.commands]]
name = "Unit tests"
cmd = "uv run pytest"
max_staleness_seconds = 3600

[[integator.commands]]
name = "Command 2"
cmd = "echo 'test 2'"
max_staleness_seconds = 10
