[integator]
push_on_success = true

[[integator.steps]]
name = "U"
cmd = "uv run pytest"
max_staleness_seconds = 1

[[integator.steps]]
name = "T"
cmd = "uv run pyright"
max_staleness_seconds = 1

[[integator.steps]]
name = "X"
cmd = "! rg -g '!integator.toml' XXX:"
