[integator]
push_on_success = true
complexity_bar_max = 100
complexity_changes_per_block = 10
complexity_threshold = 20

[[integator.commands]]
name = "U"
cmd = "uv run pytest"
max_staleness_seconds = 1

[[integator.commands]]
name = "T"
cmd = "uv run pyright"
max_staleness_seconds = 1

[[integator.commands]]
name = "X"
cmd = "! rg -g '!integator.toml' XXX: ."
