[integator]
test = 2

[[integator.commands]]
name = "Unit test"
cmd = "uv run pytest"
max_staleness_seconds = 0

[[integator.commands]]
name = "Command 2"
cmd = "echo 'test 2'"
max_staleness_seconds = 10
