[integator]
push_on_success = true
complexity_bar_max = 100
complexity_changes_per_block = 10
complexity_threshold = 20
source_dir = "/Users/mabe/Git/integator"

[[integator.commands]]
name = "Unit tests"
cmd = "uv run pytest"
max_staleness_seconds = 1

[[integator.commands]]
name = "Types"
cmd = "uv run pyright"
max_staleness_seconds = 1
